version: '3.1'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hsan
      MONGO_INITDB_ROOT_PASSWORD: hsan
      MONGO_INITDB_DATABASE: hsan
    volumes:
      - ~/db:/data/db
  app:
    image: 'springbootapp'
    build: .
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: mongodb://hsan:hsan@mongodb:27017/gte3?authSource=admin&readPreference=primaryPreferred&directConnection=true
    depends_on:
      - mongodb