apiVersion: v1
kind: ConfigMap
metadata:
  name: student-configmap
data: 
  SPRING_DATASOURCE_URL: mongodb://hsan:hsan@mongo-service:27017/hsan?authSource=admin&readPreference=primaryPreferred&directConnection=true
