apiVersion: v1
kind: ConfigMap
metadata:
  name: student-configmap
data: 
  SPRING_DATASOURCE_URL: mongodb://gte3:gte3@mongo-service:27017/gte3?authSource=admin&readPreference=primaryPreferred&directConnection=true
