apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom: 
              secretKeyRef: 
                name: mongo-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mongo-secret
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGO_INITDB_DATABASE
            value: "gte3"
      volumes:  # This is a key part that was missing
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc     
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb 
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017



